### ISSUE TITLE
Mainnet nodes are making >4mm rpc calls / day over rpc to base. Why?

### ISSUE THREAD

**Issue by jterzis** [river-build/river#1583]
An operator is noticing >4mm rpc calls / day to Base (non-tx calls). Questions follow below.

How do Base rpc calls scale in the stream node and by which system are they constrained ? It seems there's a chain monitor in [chain_monitor.go](https://github.com/river-build/river/blob/main/core/node/crypto/chain_monitor.go#L365) that runs for xchain against Base chainId 8453 with a poll loop that calls eth_getFilterLogs to process callbacks, but it's unclear whether the ChainMonitor polling loop constrains eth_call (non-transactional) rpc calls to Base from the stream node or whether there's another part of the system responsible for this level of throughput. 

Also, which prom metrics should be used to isolate this network activity by chainId 8453 ?
Is it:
- `chain_monitor_pollcounter`

Do we need to add lower level counters for eth calls made to base ?

**Comment by bas-vk** [comment]
The chain monitor performs `eth_getBlockByNumber` and `eth_getLogs`. It doesn't call `eth_call`. `chain_monitor_pollcounter` is plotted in a DD dashboard which shows that the chain monitor is making the expected amount of calls (~0.55 per second) on chain metrics that we have access to. I _expect_ that this is also the case for that node.

Recently stream scrubbing was introduced. Each scrub task requires multiple `eth_calls` for each channel member. There is caching logic that prevents doing the same check too often but maybe there is some misconfiguration, a bug or there are simply a lot of channel and members.

[Here is a trace that makes 1246 eth_calls in a single scrub task.](https://app.datadoghq.com/apm/trace/844bff7bdb165566667269f6b5946a7b?graphType=flamegraph&shouldShowLegend=true&sort=time&spanID=16627683471853733866&timeHint=1732180537856.3123)

**Comment by clemire** [comment]
> The chain monitor performs `eth_getBlockByNumber` and `eth_getLogs`. It doesn't call `eth_call`. `chain_monitor_pollcounter` is plotted in a DD dashboard which shows that the chain monitor is making the expected amount of calls (~0.55 per second) on chain metrics that we have access to. I _expect_ that this is also the case for that node.
> 
> Recently stream scrubbing was introduced. Each scrub task requires multiple `eth_calls` for each channel member. There is caching logic that prevents doing the same check too often but maybe there is some misconfiguration, a bug or there are simply a lot of channel and members. I suspect that stream scrubbing it the major contributor to the high amount of calls.
> 
> [Here is a trace that makes 1246 eth_calls in a single scrub task.](https://app.datadoghq.com/apm/trace/844bff7bdb165566667269f6b5946a7b?graphType=flamegraph&shouldShowLegend=true&sort=time&spanID=16627683471853733866&timeHint=1732180537856.3123)

There are 415 people in this channel. Therefore 1246 calls is 3 * # of people + 1.

Every linked wallet calculation is a maximum of two calls, and for a user with no linked wallets, the space membership will be another call. So 3x the # of users is expected if each user has no linked wallets. The extra call would probably be fetching channel entitlements for the READ permission.

I checked the space itself and all roles are user entitlement roles, so once the entitlement is fetched, there should be no eth calls required to evaluate it.

**Comment by jterzis** [comment]
eth_call volume likely originating from scrubber as per @clemire . Will explore a positive/negative cache which will eliminate ~1/3 of call volume (excl linked wallets) and increasing scrubber interval as well.

**Comment by clemire** [comment]
A change was deployed [to increase scrubbing duration by 4x](https://github.com/river-build/river/commit/ad064cf89ba97ab3fedfd8a65379ca82c6d06fc9), and [isMember caching](https://github.com/river-build/river/issues/1619) was also deployed. [linked wallets caching](https://github.com/river-build/river/issues/1621) is in progress. I am also working on metrics now.

**Comment by clemire** [comment]
LInked wallets caching was merged, metrics also merged today. I will solicit RPC metrics from Unit410 after they deploy but I expect at least 4x reduction due to the frequency change for scrubbing, so I'm not worried about this.

**Comment by clemire** [comment]
I will check in again with unit410 on this one, but after a day of deployment it looks like eth calls went down about 75%, indicating that the caching didn't help much, but the scrubbing interval change was successful.

**Comment by clemire** [comment]
The decrease may have been > 75%, it's a bit hard to tell, but rpc counts for unit410s nodes have dropped to about 1 million a day, which looks reasonable. From them, "I think you can close it."

cc @jterzis, I'm closing this one out but please reopen if you have concerns.
