### ISSUE TITLE
Deploy V2 contracts

### ISSUE THREAD

**Issue by clemire** [river-build/river#553]
### Description

Deploy the architect and rule entitlement upgrades. the entitlementDataQueryable upgrade should already be deployed.

**Comment by texuf** [comment]
@giuseppecrj is this still valid? We think it's done.

**Comment by clemire** [comment]
All deployed except: on omega is one missing contract, `RuleEntitlementV2` that must be deployed and set on the space architect as one of the immutable entitlements, by next Tuesday before the client deploy to omega.
