### ISSUE TITLE
Bots - Import and export keys before and after runs

### ISSUE THREAD

**Issue by texuf** [river-build/river#603]
### Description

previous ticket: https://linear.app/hnt-labs/issue/HNT-7272/import-export-olm-device

When a user first connects to a river node, they instantiate an olm device which is saved locally and is used to derive all of the encryption keys.

For example, on start, users upload a public device key to their device key stream, the device key is derived form the olm device. Other users will encrypt messages to you using this public device key, and you can decrypt the messages with your olm device. (very loosely describes what's going on)

Another example, when a user joins a channel, they derive a group encryption key that they will use to encrypt messages to that channel, then share the session key with all the members of the channel so that they can decrypt the messages

The bots that are running in the stress test are creating new olm devices every time, and deriving new group encryption keys for every stream that they post in. This does not model real user behavior, and creates excess unnatural load and slows down the tests.

We should import and export the olm device and the group encryption keys before and after each run. 

I think we can initially save them to disc on the container, but if this doesn't work we will need a database, probably a redis instance where we can save/load these items.

Wil did the group session import export here: https://github.com/river-build/river/pull/257 we should implement the device import/export and write some tests for it, and then try it in the stress clients.

**Comment by miguel-nascimento** [comment]
#616 implements the import/export of the olm device

**Comment by texuf** [comment]
need to save to redis now that we have one running.
