### ISSUE TITLE
Add support for Gnosis Chain so we can support POAPs

### ISSUE THREAD

**Issue by heyitsfei** [river-build/river#667]
POAP - Proof of Attendance Protocol (POAP) is a non-fungible token (NFT) that can be used to gate parts of the web. POAPs are digital badges that are sent to a person's wallet as a reward for participating in an event or activity. 

POAPs are standard ERC-721 tokens minted on the POAP smart contracts.

More info about POAPs [here](https://poap.zendesk.com/hc/en-us/articles/9494654007437-What-is-POAP#:~:text=Characteristics%20of%20the%20POAP%20ecosystem&text=Since%20POAPs%20are%20NFTs%2C%20they,free%20for%20collectors%20to%20mint.). POAP collection: https://opensea.io/collection/poap-v2

Requirements

Add support for Gnosis Chain - we need all of the node operators to implement, and then a config file for [app.towns.com](http://app.towns.com/), but no code changes.

Let's ask the node operators to update config by a specific date and we can ask QA to run through the scenarios on Gnosis Chain as well to make sure it's working. 

We will support ERC-721 first then once 1155 support is up we will support that

**Comment by jterzis** [comment]
node operators informed to update by next release cycle next Tuesday
