### ISSUE TITLE
DLog - After disabling mutliline we now log way too much data 

### ISSUE THREAD

**Issue by texuf** [river-build/river#722]
### Description

Logs for this ticket are ~22MB instead of 100's of Kb https://linear.app/hnt-labs/issue/TOWNS-11109/%5Bomega%5D%5Buser-feedback%5D-everytime-i-open-towns-it-takes-me-to-same-town

I think after this change: https://github.com/river-build/river/pull/590 we no longer respect the "depth" property that was preventing us from logging entire objects.

I can think of a few quick fixes
- instead of looking at NODE_ENV we can make a new env var that we only set during stress tests 
- fix the code so that we still recurse the objects as before but we concatenate them at a later point in the logger
- re-write the logger with a better logging library (debug seems very limited)

Would be interested in hearing more. I think the highest priority is to get things working like they were before.

**Comment by miguel-nascimento** [comment]
I went with the first option for #724, but I'm interested in rewriting the logger with a better logging library
