### ISSUE TITLE
Reverting stream node version is possible under all situations

### ISSUE THREAD

**Issue by jterzis** [river-build/river#979]
**Is your feature request related to a problem? Please describe.**

Node operators have faced problems in the past downgrading stream node when an upgrade failed due to a faulty migration. Migration table is out of sync on downgrade preventing revert to a prior version. In general, during an upgrade issue, operators should be able to revert to the prior running stream node version without issue.

A particular example error message seen in the wild during a downgrade that failed due to this issue:

```
`{"time":"2024-09-05T22:10:08.647945879Z","level":"ERROR","msg":"Failed to start server","error":"NewPostgresEventStore: InitStorage: (47:DB_OPERATION_FAILURE) Error running migration
s | Failed to init store base_error: Dirty database version 5. Fix and force version.\n    schemaName = s0xb8617dfa0383c7193dde95e1ff96...."}
Error: NewPostgresEventStore: InitStorage: (47:DB_OPERATION_FAILURE) Error running migrations | Failed to init store base_error: Dirty database version 5. Fix and force version.
    schemaName = s0xb8617dfa0383c7193dde.....`
```

**Describe the solution you'd like**
Implement features in stream node allow reverting to prior versions or software and migration version. Operators should NOT have to exec into their node db to run commands against `schema_migrations` table directly.  

**Describe alternatives you've considered**

**Additional context**

**Comment by sergekh2** [comment]
if migration is left in the dirty state, manual intervention is required
