### ISSUE TITLE
Running migrations concurrently caused db failures

### ISSUE THREAD

**Issue by jterzis** [river-build/river#980]
**Describe the bug**
A node operator noticed today a bug that prevented upgrading to a new version of the software. 2 nodes upgraded concurrently against a single node DB instance. The db exited with an error, OUT OF MEMORY,  and prevented the upgrade from succeeding.  Investigate why running a migrations concurrently against a single node db causing an OUT OF MEMORY exception. The node db was reported to have 30gb of memory with no indication of memory contention around the incident time. 

**To Reproduce**

**Expected behavior**
The migrations on each node fe process should have completed successfully resulting in healthy node processes and a consistent migration state in the db. 

**Screenshots**
![2024-09-05 16 30 23](https://github.com/user-attachments/assets/bb263f51-bcd8-453e-9779-43664c5783c8)

**Desktop (please complete the following information):**

- Processor: [e.g. arm64, x86]

**Logs**

- stream node syslogs
- postgres logs
- blockchain explorer transactions

**Additional context**

**Comment by sergekh2** [comment]
#1019 is filed to improve docs
